### PR TITLE
Added Weekly Music Visualizations

### PR DESCRIPTION
**Pull request by surayashivji**
Repo: https://github.com/surayashivji/WeeklyGraphics
Website: wklymotion.com

### CODE REVIEW

**Comment by surayashivji** [comment]
Hey @willianjustenm, I'm not sure why this is failing CI?

**Comment by surayashivji** [comment]
Hey @willianjusten, I'm not sure why this is failing CI?

**Comment by willianjusten** [comment]
Hey, @surayashivji, the CI is failing because other broken links, will fix it. But I don't why, I'm having conflicts to merge your PR...I'll try to handle this separately...

**Comment by willianjusten** [comment]
I added mannualy [here](https://github.com/willianjusten/awesome-audio-visualization/commit/5b71b54d206d3f82f111b2d88db8e0e7a68acae4)

**Pull request closed without merging**
