### PR TITLE
Add Circular Audio Wave library

### PR DESCRIPTION
**Pull request by kelvinau**
I have created a library for visualizing audio data in a circular wave. Want to share it with the community. :blush:

### CODE REVIEW

**Comment by kelvinau** [comment]
Soundcloud Visualizer (http://soundscape.ivxvixviii.io/) is down so the test failed. Should I remove it from the list?

**Comment by willianjusten** [comment]
If you can, would be great.

**Comment by kelvinau** [comment]
OK just removed that

**Comment by willianjusten** [comment]
Thanks!

**Pull request merged**
